version: '3'
services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile # Adjust the context to the root of your project
    container_name: "mazda-app"

  app1:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile # Adjust the context to the root of your project
    container_name: "mazda-app-2"

  nginx:
    container_name: "mazda-app-NGINX"
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Specify the path to the NGINX config file
